# Generated by Django 4.0 on 2021-12-31 08:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=100)),
                ('product_subcategory', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_technical_specs', models.TextField()),
                ('price', models.IntegerField()),
                ('product_tag', models.CharField(max_length=50)),
            ],
        ),
    ]
