# Generated by Django 4.0 on 2022-01-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_title',
            field=models.CharField(blank=True, default='slider', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='400-200.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(blank=True, default='400-200.png', upload_to=''),
        ),
    ]
